# 数据源
server:
  port: 8000
spring:
  application:
    name: shardingjdbc-shardingtable-demo
  datasource:
    url: jdbc:mysql://localhost:3306/ypmodule?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost    # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    pool:
      max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 10          # 连接池中的最大空闲连接
      max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000
# mybatis配置
mybatis:

  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.example.my_books.model   # 实体类所在的位置
  configuration:
    map-underscore-to-camel-case: true #开启驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
